### ISSUE TITLE
How to delete an entry from an existing database

### ISSUE THREAD

**Issue by joshgabriel** [materialsproject/pymatgen-db#31]
Hi all, 

I am a new user to pymatgen-db and am trying to understand how to delete entries to a database. Is there a method (expected it to be in queryengine.py but didn't find) that implements this ? 

Thanks,
Josh

**Comment by shyuep** [comment]
pymatgen-db is essentially a "translator" between pymatgen and pymongo.
To delete entries, you can simply use the relevant pymongo commands. For example, the query engine provides the actual pymongo collection object in the collection variable. So to remove entries, you simply need to do:

```
qe = QueryEngine(....)
qe.collection.remove({criteria})
```

**Comment by shyuep** [comment]
P.S. the pymongo documentation helps in learning how to do all sorts of things to your database. See https://api.mongodb.org/python/current/
