### ISSUE TITLE
Why do all dependent packages require the exact version?

### ISSUE THREAD

**Issue by xhqu1981** [materialsproject/pymatgen-db#35]
I found in "requirements.txt" the exact version requirement is specified. e.g. monty==0.7.0. However, in pymatgen a newer version is required, i.e., monty==0.8.1. This inconsistence makes PyCharm keeps reminding me that the requirement is not satisfied. Is there any reason why the minimum version requirement (e.g. monty>=0.70) doesn't work?

**Comment by shyuep** [comment]
It is generally a good practice to pin requirements to exact versions to ensure that dependencies are properly installed. I can update the pymatgen-db ones.
