### ISSUE TITLE
Optional Sort Method on query_engine.query method

### ISSUE THREAD

**Issue by alayers2** [materialsproject/pymatgen-db#36]
The query method already supports the index, limit, and distinct_key options. It would be convenient as well to have an option to pass in something along the lines of `sort={'date_created':1}` to enable queries such as "find the 10 most recently processed entries".

**Comment by shyuep** [comment]
Thanks for the sughestion. I have done you one better. Instead of artificially adding index, limit, sort, etc., I have used kwargs which is a passthrough to find. That will allow you to use all the usual kwargs supported by pymongo.collection.find to control the behavior of query.

**Comment by alayers2** [comment]
Perfect! I was going to branch and add something myself, but you were so fast I didn't have a chance 👍
