### ISSUE TITLE
runserver command doesn't exist in version installed from pip

### ISSUE THREAD

**Issue by chiahaoliu** [materialsproject/pymatgen-db#38]
I tried to follow the instruction in ``README`` page and I can follow up to ``mgdb runsercer -c db.json``, which gives me an error about saying this argument is not available. However, I can find this argument available in release ``0.5.1`` (with minor error from ``django``)

any idea? Thanks :)

**Comment by shyuep** [comment]
Sorry, the README is outdated. I have updated it to remove the GUI, which has been replaced by flamyngo (https://github.com/materialsvirtuallab/flamyngo)
