### ISSUE TITLE
No authenticate method for 'Database' object

### ISSUE THREAD

**Issue by JonathanSchmidt1** [materialsproject/pymatgen-db#91]
**Describe the bug**

The authentication in the query engine:
```
        if user:
            self.db.authenticate(user, password)
```
does not work any more as: 
pymongo.database.Database.authenticate() and pymongo.database.Database.logout() were removed in MongoDB 3.6+
https://pymongo.readthedocs.io/en/stable/migrate-to-pymongo4.html#database-authenticate-and-database-logout-are-removed
Changing to:
```
         if connection is None:
            if self.replicaset:
                self.connection = pymongo.MongoClient(self.host, self.port, replicaset=self.replicaset, username=user, password=password)
            else:
                self.connection = pymongo.MongoClient(self.host, self.port, username=user, password=password)
```
solved the issue for me. I assume this also needs to be changed in /pymatgen/db/creator.py but I did not test the latter.
If you want to keep it in the mongoDB version <3.6+ state it would be great if you could add that to the requirements for future users.

ubuntu, db version v6.0.7

**Comment by shyuep** [comment]
Thanks. I just pushed a fix.
